ALTER TABLE AMONESTA(

	ADD CONSTRAINT DOM_AM_TARGETA CHECK AM_AMARILLA/ROJA 
										IN ('AMARILLA','ROJA')),
	ADD CONSTRAINT FK_AM_ARBITRO FOREIGN KEY (AM_NOMBRE_ARBITRO)
			REFERENCES ARBITRO,		
	ADD CONSTRAINT FK_AMONESTA_JUGADOR FOREIGN KEY 
			(AM_NOMBRE_JUGADOR)
			REFERENCES JUGADOR
	ADD CONSTRAINT PK_AMONESTA PRIMARY KEY(AM_NOMBRE_JUGADOR, AM_NOMBRE_ARBITRO)
);
			
ALTER TABLE ANOTA_GOL(

	ADD CONSTRAINT DOM_AG_TIPO CHECK (AG_TIPO IN
	 ('PIERNA DERECHA','PIERNA IZQUIERDA','DE CABEZA','DE PENALTI',
	 'DE TIRO LIBRE','EN PROPIA PUERTA')),
	 ADD CONSTRAINT FK_ANOTA_GOL_JUGADOR FOREIGN KEY 
			(AG_NOMBRE_JUGADOR),
			REFERENCES JUGADOR,
	ADD CONSTRAINT FK_ANOTA_GOL_PARTIDO FOREIGN KEY 
			(AG_ID_PARTIDO,AG_NOMBRE_COPA,AG_TEMPORADA)
			REFERENCES PARTIDO,		
	ADD CONSTRAINT DIST_JUG CHECK(AG_NOMBRE_JUGADOR <> AG_ASISTENTE)
	
	ADD CONSTRAINT PK_AMONESTA PRIMARY KEY(AG_NOMBRE_JUGADOR, 
		AG_ID_PARTIDO,AG_NOMBRE_COPA,AG_TEMPORADA)
	
);		

ALTER TABLE ARBITRO(

	ADD CONSTRAINT PK_ARBITRO PRIMARY KEY (AR_NOMBRE)
);
	
ALTER TABLE COPA(
	
	ADD CONSTRAINT PK_ARBITRO PRIMARY KEY (CO_NOMBRE,CO_TEMPORADA),
	ADD CONSTRAINT DOM_CO_ETAPA CHECK (CO_ETAPA 
		IN ('FASE PREVIA','PRIMERA FASE','OCTAVOS DE FINAL',
			'DCUARTOS DE FINAL','SEMIFINAL','FINAL'),
	
);

ALTER TABLE CLUB(

	ADD CONSTRAINT PK_ARBITRO PRIMARY KEY (CL_NOMBRE_C),
	ADD CONSTRAINT VIGENICA_ENT CHECK (CL_F_INICIO_ENT < CL_F_FINAL_ENT)
);

ALTER TABLE ESTADIO(

	ADD CONSTRAINT PK_ESTADIO PRIMARY KEY(ES_NOMBRE),
	ADD CONSTRAINT FK_ESTADIO_CLUB FOREIGN KEY(ES_NOMBRE_CLUB ) 
		REFERENCES CLUB
		
ALTER TABLE JUEGA(

	ADD CONSTRAINT DOM_JA_ETAPA_P CHECK 
		(JA_ETAPA_P IN ('FASE PREVIA','PRIMERA FASE','OCTAVOS DE FINAL',
		'DCUARTOS DE FINAL','SEMIFINAL','FINAL')),
	ADD CONSTRAINT FK_JUEGA_JUGADOR FOREIGN KEY (JA_NOMBRE) 
		REFERENCES JUGADOR,
	ADD CONSTRAINT FK_JUEGA_PARTIDO FOREIGN KEY 
		(JA_ID,JA_JA_N_TROFEO,JA_TEMPORADA) REFERENCES PARTIDO,	
	ADD CONSTRAINT PK_JUEGA PRIMARY KEY 
		(JA_NOMBRE,JA_ID,JA_JA_N_TROFEO,JA_TEMPORADA),
	ADD CONSTRAINT TIEMPO_JUEGO CHECK(JA_I_MINUTO < JA_F_MINUTO));
			
ALTER TABLE JUGADOR(

	ADD CONSTRAINT PK_JUGADOR PRIMARY KEY(JR_NOMBRE),
	ADD CONSTRAINT FK_JUGADOR_CLUB FOREIGN KEY(JR_NOMBRE_CLUB) 
		REFERENCES CLUB,
	ADD CONSTRAINT DOM_JR_DIE_ZUR CHECK 
		(JR_DIE_ZUR IN ('DIESTRO','ZURDO','AMBIDIESTRO')),
	ADD CONSTRAINT CHECK(JR_PESO > 0),
	ADD CONSTRAINT CHECK(JR_ESTATURA > 0),
	ADD CONSTRAINT CHECK(JR_F_INICIO < JR_F_FINAL)
