CREATE TABLE AMONESTA(

AM_NOMBRE_ARBITRO VARCHAR(14),
AM_NOMBRE_JUGADOR VARCHAR(14),
AM_AMARILLA/ROJA VARCHAR(14),
AM_MINUTO TIMESTAMP,			
);

CREATE TABLE ANOTA_GOL(
	
AG_NOMBRE_JUGADOR 			VARCHAR(20),
AG_ID_PARTIDO				INT(3),
AG_N_TROFEO					VARCHAR(14),
AG_TEMPORADA				VARCHAR(9),
AG_MINUTO					TIMESTAMP,
AG_TIPO						VARCHAR(20),
AG_ASISTENTE				VARCHAR(20)
);

CREATE TABLE ARBITRO(

AR_NOMBRE					VARCHAR(20),
AR_NACIONALIDAD				VARCHAR(20),
AR_ID						INT(3),
AR_NOMBREC					VARCHAR(20),
AR_TEMPORADA				VARCHAR(9)

);

CREATE TABLE COPA(

CO_NOMBRE					VARCHAR(14),
CO_TEMPORADA				VARCHAR(9),
CO_N_TROFEO					VARCHAR(14),
CO_ORGANIZACION				VARCHAR(14),
CO_CAMPEON					VARCHAR(14),
CO_ETAPA					VARCHAR(14) 
);

CREATE TABLE COPA_PAISES(

COPA_PAISES					VARCHAR(40) 
);

CREATE TABLE COPA_ETAPA( 
);

CREATE TABLE CLUB(
CL_NOMBRE_C					VARCHAR(40),
CL_CIUDAD					VARCHAR(12),
CL_AÑO_F					NUMERIC(4),
CL_PAIS						VARCHAR(12),
CL_NOMBRE_ENT 				VARCHAR(40),
CL_F_INICIO_ENT 			TIMESTAMP,
CL_F_FINAL_ENT				TIMESTAMP,
);

CREATE TABLE ESTADIO(

ES_NOMBRE,
ES_NOMBRE_CLUB,
ES_CAPACIDAD INT(6),

);

CREATE TABLE JUEGA(


JA_NOMBRE					VARCHAR(20),
JA_ID						INT(3),
JA_N_TROFEO					VARCHAR(20),
JA_TEMPORADA				VARCHAR(9),
JA_JORNADA_P				VARCHAR(20),
JA_ETAPA_P					INT(3),
JA_I_MINUTO					TIMESTAMP,
JA_F_MINUTO					TIMESTAMP,
JA_POSICION					VARCHAR(20),	

);

CREATE TABLE JUGADOR(

JR_NOMBRE					VARCHAR(20),
JR_NOMBRE_CLUB 				VARCHAR(20),
JR_ESTATURA					INT(2),
JR_DIE_ZUR					VARCHAR(10),
JR_NACIONALIDAD				VARCHAR(20),
JR_PESO						INT(3),
JR_F_INICIO					TIMESTAMP,
JR_F_FINAL					TIMESTAMP,
JR_RECISION					INT(10),
JR_SALARIO					INT(10),
 
);

CREATE TABLE LIGA(
LG_NOMBRE					VARCHAR(14),
LG_TEMPORADA				VARCHAR(9),
LG_N_TROFEO					VARCHAR(14),
LG_ORGANIZACION				VARCHAR(14),
LG_CAMPEON					VARCHAR(14),
LG_NUMERO_ETAPA				INT(2),
LG_PAIS						VARCHAR(14),

CONSTRAINT PK_LIGA PRIMARY KEY(LG_NOMBRE, LG_TEMPORADA)

);

CREATE TABLE MODERADO(

MD_NOMBRE_ARBITRO			VARCHAR(20),
MD_ID						INT(3),
MD_N_TROFEO					VARCHAR(14),
MD_TEMPORADA				VARCHAR(9)

);

CREATE TABLE PARTIDO(

PD_ID						INT(3),
PD_N_TROFEO					VARCHAR(14),
PD_TEMPORADA				INT(4),
PD_NOMBRE_LOCAL				VARCHAR(20) CONSTRAINT FK_PARTIDO_CLUB
										REFERENCES CLUB,
PD_NOMBRE_VISITANTE			VARCHAR(20) CONSTRAINT FK_PARTIDO_CLUB
										REFERENCES CLUB,
PD_GANADOR					VARCHAR(20),
PD_MARCADOR					VARCHAR(4),
PD_FECHA					TIMESTAMP,
PD_ASISTENCIA				INT(6),
PD_NOMBRE_ARBITRO			VARCHAR(20) CONSTRAINT FK_PARTIDO_ARBITRO
										REFERENCES ARBITRO,

CONSTRAINT PK_PARTIDO PRIMARY KEY(PD_ID),
CONSTRAINT FK_PARTIDO_COMPETENCIA FOREIGN KEY 
				(PD_N_TROFEO,PD_TEMPORADA)
					REFERENCES COMPETENCIA,

CHECK(PD_NOMBRE_LOCAL <> PD_NOMBRE_VISITANTE),
CHECK(PD_GANADOR = PD_NOMBRE_LOCAL or PD_GANADOR = PD_NOMBRE_VISITANTE)
 
);
