ALTER TABLE CLUB

	-- SE USA EL NOMBRE DEL CLUB COMO CLAVE PRIMARIA

	ADD CONSTRAINT PK_CLUB PRIMARY KEY (CL_NOMBRE_CLUB),
	
	-- LA FECHA DE INICIO DEL ENTRENADOR DEBE SER ANTERIOR A LA FECHA EN LA QUE
	-- FINALIZA SU CONTRATO
	
	ADD CONSTRAINT VIGENICA_ENT CHECK (CL_F_INICIO_ENT < CL_F_FINAL_ENT),
	
	-- LA FECHA EN LA QUE UN ENTRENADOR EMPIEZA EN UN CLUB DEBE SER MAYOR A LA
	-- FECHA DE FUNDACION DEL CLUB
	
	ADD CONSTRAINT CONTRATO_ENT CHECK (CL_F_INICIO_ENT > CL_AÑO_F);
	
--END ALTER TABLE CLUB
	
ALTER TABLE JUGADOR

	-- SE USA EL NOMBRE DEL JUGADOR COMO CLAVE PRIMARIA

	ADD CONSTRAINT PK_JUGADOR PRIMARY KEY(JR_NOMBRE),
	
	-- EL NOMBRE DEL CLUB HACE RFERENCIA A LA TABLACLUB
	
	ADD CONSTRAINT FK_JUGADOR_CLUB FOREIGN KEY(JR_CLUB) 
		REFERENCES CLUB,
		
	-- SE DEFINE EL RANGO DE "DIE_ZUR", YA QUE SOLO SE PUEDE SER DIESTRO,ZURDO
	-- O AMBIDIESTRO	
		
	ADD CONSTRAINT DOM_JR_DIE_ZUR CHECK 
		(JR_DIE_ZUR IN ('DIESTRO','ZURDO','AMBIDIESTRO')),
	
	-- EL PESO Y LA ESTATURA DEBEN SER ENTEROS POSITIVOS	
		
	ADD CONSTRAINT EXP_JR_PESO CHECK(JR_PESO > 0),
	ADD CONSTRAINT EXP_JR_ALTURA CHECK(JR_ALT > 0),
	ADD CONSTRAINT EXP_JR_SALARIO CHECK(JR_SALARIO > 0),
	
	-- LA FECHA DE INICIO DEL CONTRATO DEL JUGADOR DEBE SER ANTERIOR A LA FECHA
	-- EN LA QUE FINALIA
	
	ADD CONSTRAINT EXP_JR_F_INICIO CHECK(JR_F_INI < JR_F_FIN);
	
--END ALTER TABLE JUGADOR
	
ALTER TABLE ARBITRO

	-- SE USA EL NOMBRE DEL ARBITRO COMO CLAVE PRIMARIA

	ADD CONSTRAINT PK_ARBITRO PRIMARY KEY (AR_NOMBRE);
	
--END ALTER TABLE ARBITRO	
	
ALTER TABLE COMPETENCIA

	-- SE USA EL NOMBRE DE LA COMPETENCIA Y SU TEMPORADA PARA DEFINIR LA 
	-- COMPETENCIA (EJ: CHAMPIONS 2009)

	ADD CONSTRAINT PK_COMPETENCIA PRIMARY KEY (COM_NOMBRE,COM_TEMPORADA),
	
	-- SI UNA COMPETENCIA ES UNA LIGA NO PUEDE SER UNA COPA Y VICEVERSA
	
	ADD CONSTRAINT EXP_COMPETENCIA CHECK ((NOT(COM_LIGA = NULL) OR 
		COM_COPA <> NULL)
			AND ((NOT(COM_COPA = NULL) OR COM_LIGA <> NULL))),
		
	-- SE DEFINE EL RANGO DE TIPO
		
	ADD CONSTRAINT DOM_TIPO CHECK (COM_TIPO IN ('Copa','Liga')),	
	
	-- SE DEFINE EL TIPO
		
	ADD CONSTRAINT TIPO_COMPETENCIA CHECK ((NOT(COM_LIGA <> NULL) OR 
		(COM_TIPO = 'Liga')) AND (NOT(COM_COPA <> NULL) 
			OR (COM_TIPO = 'Copa')));	
			
--END ALTER TABLE COMPETENCIA
	
ALTER TABLE PARTIDO

	-- EL NOMBRE DE LA COMPETENCIA Y SU TEMPORADA HACEN REFERENCIA A LA 
	-- TABLA COMPETENCIA

	ADD CONSTRAINT FK_PARTIDO_COMPETENCIA FOREIGN KEY 
				(PD_NOMBRECOMP,PD_TEMPORADA)
					REFERENCES COMPETENCIA,
	
	-- EL NOMBRE DEL CLUB VISITANTE Y EL DEL LOCAL HACEN REFERENCIA A LA TABLA
	-- CLUB				
					
	ADD CONSTRAINT FK_PARTIDO_CLUB_LOCAL FOREIGN KEY(PD_NOMBRE_LOCAL) 
		REFERENCES CLUB,
	ADD CONSTRAINT FK_PARTIDO_CLUB_VIS FOREIGN KEY(PD_NOMBRE_VIS) 
				REFERENCES CLUB,
	
	-- EL NOMBRE DEL ARBITRO HACE REFERENCIA A LA TABLA ARBITRO			
				
	ADD CONSTRAINT FK_PARTIDO_ARB FOREIGN KEY(PD_NOMBRE_ARB)
										REFERENCES ARBITRO,
										
	-- SE TOMA DE CLAVE PRIMARIA EL ID DEL PARTIDO JUNTO CON EL NOMBRE DE LA 
	-- COMPETENCIA Y SU TEMPORADA (EJ: PARTIDO 09 DE LA LIGA ESPAÑOLA 2014)
	
	ADD CONSTRAINT PK_PARTIDO PRIMARY KEY (PD_ID,PD_NOMBRECOMP,PD_TEMPORADA),

	-- EL EQUIPO LOCAL DEBE SER DIFERENTE AL VISITANTE

	ADD CHECK(PD_NOMBRE_LOCAL <> PD_NOMBRE_VIS),
	
	-- TIENE QUE HABER UN GANADOR
	
	ADD CHECK(PD_GANADOR = PD_NOMBRE_LOCAL or PD_GANADOR = PD_NOMBRE_VIS);	
	
--END ALTER TABLE PARTIDO								

ALTER TABLE AMONESTA

	ADD CONSTRAINT DOM_AM_TARGETA CHECK (AM_AMARILLA_ROJA 
										IN ('AMARILLA','ROJA')),
	ADD CONSTRAINT FK_AM_PARTIDO FOREIGN KEY (AM_ID_PARTIDO,AM_NOMBRECOMP,AM_TEMPORADA)
			REFERENCES PARTIDO,		
	ADD CONSTRAINT FK_AMONESTA_JUGADOR FOREIGN KEY 
			(AM_NOMBRE_JUGADOR)
			REFERENCES JUGADOR,
	ADD CONSTRAINT PK_AMONESTA PRIMARY KEY(AM_NOMBRE_JUGADOR,AM_ID_PARTIDO,AM_NOMBRECOMP,AM_TEMPORADA),
	ADD CONSTRAINT LI_AM_ID_PARTIDO CHECK (AM_ID_PARTIDO > 0);
	
--END ALTER TABLE AMONESTA	
			
ALTER TABLE ANOTA_GOL

	ADD CONSTRAINT DOM_AG_TIPO CHECK (AG_TIPO IN
	 ('PIERNA DERECHA','PIERNA IZQUIERDA','DE CABEZA','DE PENALTI',
	 'DE TIRO LIBRE','EN PROPIA PUERTA')),
	ADD CONSTRAINT FK_ANOTA_GOL_JUGADOR FOREIGN KEY (AG_NOMBRE_JUGADOR)
			REFERENCES JUGADOR,
	ADD CONSTRAINT FK_ANOTA_GOL_PARTIDO FOREIGN KEY 
			(AG_ID_PARTIDO,AG_NOMBRECOMP,AG_TEMPORADA)
			REFERENCES PARTIDO,		
	ADD CONSTRAINT DIST_JUG CHECK(AG_NOMBRE_JUGADOR <> AG_ASISTENTE),
	ADD CONSTRAINT EXP_AG_ID_PARTIDO CHECK (AG_ID_PARTIDO >= 0),
	ADD CONSTRAINT PK_ANOTA_GOL PRIMARY KEY(AG_NOMBRE_JUGADOR, 
		AG_ID_PARTIDO,AG_NOMBRECOMP,AG_TEMPORADA);
		
--END ALTER TABLE ANOTA_GOL
	
ALTER TABLE COPA
	
	-- EL NOMBRE DE LA COMPETENCIA Y LA TEMPORADA SON LAS CLAVES PRIMARIAS Y
	-- ADEMAS HACEN REFERENCIA A LA TABLA COMPETENCIA
	
	ADD CONSTRAINT PK_COPA PRIMARY KEY (CO_NOMBRE,CO_TEMPORADA),
	ADD CONSTRAINT FK_COPA_COMPENTENCIA FOREIGN KEY(CO_NOMBRE,CO_TEMPORADA)
										REFERENCES COMPETENCIA;

--END ALTER TABLE COPA

ALTER TABLE COPA_PAISES

	-- EL NOMBRE DE LA COPA Y SU TEMPORADA HACEN REFERENCIA A LA TABLA COPA
	
	ADD CONSTRAINT FK_COPA_PAISES_COPA FOREIGN KEY(CP_NOMBRE,CP_TEMPORADA) REFERENCES COPA;
	
--END ALTER TABLE COPA_PAISES	
	
ALTER TABLE COPA_ETAPA

	-- EL NOMBRE DE LA COPA Y SU TEMPORADA SON LAS CLAVES PRIMARIAS PARA ESTA
	-- LISTA DE ETAPAS

	ADD CONSTRAINT PK_COPA_ETAPA PRIMARY KEY (CE_NOMBRE,CE_TEMPORADA),
	
	-- SE DEFINE LAS POSIBLES ETAPAS DE UNA COPA
	
	ADD CONSTRAINT DOM_CE_ETAPA CHECK (CE_ETAPA 
		IN ('FASE PREVIA','PRIMERA FASE','OCTAVOS DE FINAL',
			'DCUARTOS DE FINAL','SEMIFINAL','FINAL'));

--END ALTER TABLE COPAS_ETAPA

ALTER TABLE ESTADIO

	-- EL NOMBRE DEL ESTADIO ES LA CLAVE PRIMARIA (EJ: EL SANTIAGO BERNAVEU)

	ADD CONSTRAINT PK_ESTADIO PRIMARY KEY (ES_NOMBRE),
	
	-- EL NOMBRE DEL CLUB HACE REFERENCIA A LA TABLA CLUB
	
	ADD CONSTRAINT FK_ESTADIO_CLUB FOREIGN KEY(ES_NOMBRE_CLUB) 
		REFERENCES CLUB;
		
--END ALTER TABLE ESTADIO		
		
ALTER TABLE JUEGA

	-- EL NOMBRE DEL JUGADOR QUE JUEGA HACE REFERENCIA A LA TABLA JUGADOR

	ADD CONSTRAINT FK_JUEGA_JUGADOR FOREIGN KEY (JA_NOMBRE) 
		REFERENCES JUGADOR,
		
	-- EL NOMBRE DE LA COMPETENCIA, SU TEMPORADA E IDENTIFICACION HACEN 
	-- REFERENCIA A LA TABLA PARTIDO
	
	ADD CONSTRAINT FK_JUEGA_PARTIDO FOREIGN KEY 
		(JA_ID,JA_NOMBRECOMP,JA_TEMPORADA) REFERENCES PARTIDO,	
		
	-- SE ELIJE DE CLAVE PRIMARIA AL NOMBRE DEL JUGADOR, EL ID DEL PARTIDO, SU
	-- COMPETENCIA Y SU TEMPORADA (EJ: PEPE JUEGA EN EL PARTIDO 3 DEL MUNDIAL
	-- 2018)	
		
	ADD CONSTRAINT PK_JUEGA PRIMARY KEY 
		(JA_NOMBRE,JA_ID,JA_NOMBRECOMP,JA_TEMPORADA),
		
	-- EL MINUTO EN EL QUE ENTRA A JUGAR EL JUGADOR DEBE SER ANTES DEL MINUTO
	-- EN EL QUE SALE
		
	ADD CONSTRAINT TIEMPO_JUEGO CHECK(JA_I_MINUTO < JA_F_MINUTO);

			
ALTER TABLE LIGA

	-- EL NOMBRE DE LA COMPETENCIA Y LA TEMPORADA SON LAS CLAVES PRIMARIAS Y
	-- ADEMAS HACEN REFERENCIA A LA TABLA COMPETENCIA

	ADD CONSTRAINT PK_LIGA PRIMARY KEY (LG_NOMBRE,LG_TEMPORADA),
	ADD CONSTRAINT FK_LIGA_COMPENTENCIA FOREIGN KEY(LG_NOMBRE,LG_TEMPORADA)
										REFERENCES COMPETENCIA;	

--END ALTER TABLE LIGA

